dist: trusty
before_install:
  - npm install -g npm@latest
  - npm set progress=false
language: node_js
node_js:
  - "5.7"
  - "4.3"
  - "3.3"
  - "0.10"
script: npm run test:ci
addons:
  sauce_connect: true
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
