language: node_js
node_js:
- '0.8'
cache:
  directories:
  - node_modules
after_script:
  - travis-notify-geckoboard -a $GECKOBOARD_API_KEY -w $GECKOBOARD_WIDGET_KEY
before_install:
  - npm install -g npm@1.4.13
before_script:
  - npm install -g travis-notify-geckoboard
env:
  global:
  - secure: W4h/LYjYBWO6UMY7itLvbwzqs5Ty7LH0Q9Ee4bZGfM0dlTUTID1nIyfv4vx6jiKzc48ic7bJAAIzCiz6hEBtEubRDzk1ZlU2dpzBEEeyUhr3fS24Jo+YmvI61YOFWOVQQVIOAVc3ni/QOwzSE63tq96OoTFgJPERz9liBxJV8EU=
  - secure: HL25hBH/KY2KUetynrsnry0giXfNcjvPbzSKZhcCfP3B1uWqNJ9ZZehgmEoMZM0NHp12+j/RmuWfJhm3nclkFOsMBtaUaM1wzWMRa9PKN2Lz1UX2BmiChwFkB7HuGVnlkJ/3Dez0MXua+BIdUeHQ1FjZrmsJQNifFbmBisqo0LE=
  - secure: "iknUXyiQ9r6ZI9biq8tRqxXlbEO5oRoUSB0PX4AICIGYQRG0y4dwiILI4cea4+4y9piFWkgqSo8R2mOvnVbdSI4LpGASQuXp+L0rBgNVzu7RfaX5TmyHsmqLY6ELzYMjC12yRYL/22j4vc/iSB3AZHoOdLh1tBQSrdfwThY2xFM=" # GECKOBOARD_API_KEY
  - secure: "mrj4GqXWKOVnQVp4d18O852JCk9r1EXymJ9or1NTurjhclvvrzSKGmOigl8iBDCS6H51XFkvCEhqLzWN0Q0w/qnjEjiFC0JrYEmuuBJvJ2PUuZh5gH7B669ulTPZUc/53ZHlEMDXr+EfYs0UzjPM0hgVhxxvtyoTRwJh5mOZ2uk=" # GECKOBOARD_WIDGET_KEY
notifications:
  flowdock:
    - secure: lKoJdDX1B34uMyuE2EQFihyNUEQ2nLfM7esCDHcCjOOHSc4DtzxduDmCEv1a6Zw6T//sTo/ZR35ywEzdQuqFYy7oGuwJnnfseX4wgx8weH+Gq5K7MErtwIcqCJGOqfrXreItuJ394JqiMzhhcWRHScrsKf4/iDlOab28iuvWiV4=
